### ISSUE TITLE
Recent update Shiny App no longer works

### ISSUE THREAD

**Issue by ThomSoer** [vibbits/mec-shiny-apps#4]
I don't know when this happened but the shiny app is not launching (immediately crashes). App worked fine before (I would say last time I used it was September 2023 but that is a rough estimate. I tried re rolling back to a previous version of R (4.2.3) and still doesn't work. Both releases v1.1 and v1.2 crashes everytime with the following error. 

I need to use the shiny app because I am trying to load >300 plots of metabolites and using the website, the download isn't going through if there are too many metabolites. 

Any help or advice would be appreciated. Thanks.

------------------------------------------------------------------------------------------
Warning: Error in vroom::vroom: `file` is not one of the supported inputs:
• A filepath or character vector of filepaths
• A connection or list of connections
• Literal or raw input
  128: <Anonymous>
  127: signalCondition
  126: signal_abort
  125: rlang::abort
  124: cli::cli_abort
  123: standardise_path
  122: vroom::vroom
  **121: <reactive:upload_tb> [~PATH/Functions and modules/TraVis_input.R#141]**           #Error here?
  105: upload_tb
   **97: renderText [~PATH/Functions and modules/TraVis_input.R#162]**                 #Error here?
   96: func
   83: renderFunc
   82: output$input-input_valid
    1: shiny::runApp
**Warning: Error in vroom::vroom: `file` is not one of the supported inputs:**
• A filepath or character vector of filepaths
• A connection or list of connections
• Literal or raw input

**Comment by SamDeCraemer** [comment]
My apologies for the long wait. I am not sure why the app stopped working as I have not changed it. I am working on version 1.31 of the online app and will generate a new version release for offline use. 

You could also download the github repository as it is, make an r project in Github\mec-shiny-apps\shiny-server\TraVisPies, and use it to run the app.R script in that folder and make use of the updated version offline. If the timeout issue still occurs even offline (never tested), you can then change line 31 in the app.R script to simply save files locally instead of generating them in a temporary file for later download. This is probably for the best in any case. Simply set local_version to true:
`local_version<-TRUE`

Otherwise, all I can advise is to only download a limited amount of plots at once to avoid a server timeout.

**Comment by SamDeCraemer** [comment]
The online TraVis pies tool has been updated to v1.31, and that version has been added as a release. I also attempted to lengthen the time-out for figure downloads to 5 minutes, so you should be able to download more images than previously possible with the online tool (but perhaps still not multiple hundreds at once).

If you encounter any other issue, feel free to open a different thread!
